name: atom-to-atom-mapping

channels:
  - conda-forge

dependencies:
  - importlib_resources
  - pip
  - python=3.8
  - rdkit
  - tqdm
  - pip:
      - chython
      - chytorch
      - chytorch-rxnmap
      - epam.indigo
      - localmapper
      - pqdm
      - rxnmapper
