name: atom-to-atom-mapping-env

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.8
  - rdkit
  - tqdm
  - pip:
    - chython
    - chytorch
    - chytorch-rxnmap
    - epam.indigo
    - localmapper
    - pqdm
    - rxnmapper
